package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/kgosse/shop-back/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Role)
// DB Table: Plural (roles)
// Resource: Plural (Roles)
// Path: Plural (/roles)
// View Template Folder: Plural (/templates/roles/)

// RolesResource is the resource for the Role model
type RolesResource struct {
	buffalo.Resource
}

// List gets all Roles. This function is mapped to the path
// GET /roles
func (v RolesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	roles := &models.Roles{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Roles from the DB
	if err := q.All(roles); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, roles))
}

// Show gets the data for one Role. This function is mapped to
// the path GET /roles/{role_id}
func (v RolesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Role
	role := &models.Role{}

	// To find the Role the parameter role_id is used.
	if err := tx.Find(role, c.Param("role_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, role))
}

// New renders the form for creating a new Role.
// This function is mapped to the path GET /roles/new
func (v RolesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Role{}))
}

// Create adds a Role to the DB. This function is mapped to the
// path POST /roles
func (v RolesResource) Create(c buffalo.Context) error {
	// Allocate an empty Role
	role := &models.Role{}

	// Bind role to the html form elements
	if err := c.Bind(role); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(role)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, role))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Role was created successfully")

	// and redirect to the roles index page
	return c.Render(201, r.Auto(c, role))
}

// Edit renders a edit form for a Role. This function is
// mapped to the path GET /roles/{role_id}/edit
func (v RolesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Role
	role := &models.Role{}

	if err := tx.Find(role, c.Param("role_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, role))
}

// Update changes a Role in the DB. This function is mapped to
// the path PUT /roles/{role_id}
func (v RolesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Role
	role := &models.Role{}

	if err := tx.Find(role, c.Param("role_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Role to the html form elements
	if err := c.Bind(role); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(role)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, role))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Role was updated successfully")

	// and redirect to the roles index page
	return c.Render(200, r.Auto(c, role))
}

// Destroy deletes a Role from the DB. This function is mapped
// to the path DELETE /roles/{role_id}
func (v RolesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Role
	role := &models.Role{}

	// To find the Role the parameter role_id is used.
	if err := tx.Find(role, c.Param("role_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(role); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Role was destroyed successfully")

	// Redirect to the roles index page
	return c.Render(200, r.Auto(c, role))
}
