package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/kgosse/training/golang/src/projects/shop/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Wishlist)
// DB Table: Plural (wishlists)
// Resource: Plural (Wishlists)
// Path: Plural (/wishlists)
// View Template Folder: Plural (/templates/wishlists/)

// WishlistsResource is the resource for the Wishlist model
type WishlistsResource struct {
	buffalo.Resource
}

// List gets all Wishlists. This function is mapped to the path
// GET /wishlists
func (v WishlistsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	wishlists := &models.Wishlists{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Wishlists from the DB
	if err := q.All(wishlists); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, wishlists))
}

// Show gets the data for one Wishlist. This function is mapped to
// the path GET /wishlists/{wishlist_id}
func (v WishlistsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Wishlist
	wishlist := &models.Wishlist{}

	// To find the Wishlist the parameter wishlist_id is used.
	if err := tx.Find(wishlist, c.Param("wishlist_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, wishlist))
}

// New renders the form for creating a new Wishlist.
// This function is mapped to the path GET /wishlists/new
func (v WishlistsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Wishlist{}))
}

// Create adds a Wishlist to the DB. This function is mapped to the
// path POST /wishlists
func (v WishlistsResource) Create(c buffalo.Context) error {
	// Allocate an empty Wishlist
	wishlist := &models.Wishlist{}

	// Bind wishlist to the html form elements
	if err := c.Bind(wishlist); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(wishlist)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, wishlist))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Wishlist was created successfully")

	// and redirect to the wishlists index page
	return c.Render(201, r.Auto(c, wishlist))
}

// Edit renders a edit form for a Wishlist. This function is
// mapped to the path GET /wishlists/{wishlist_id}/edit
func (v WishlistsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Wishlist
	wishlist := &models.Wishlist{}

	if err := tx.Find(wishlist, c.Param("wishlist_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, wishlist))
}

// Update changes a Wishlist in the DB. This function is mapped to
// the path PUT /wishlists/{wishlist_id}
func (v WishlistsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Wishlist
	wishlist := &models.Wishlist{}

	if err := tx.Find(wishlist, c.Param("wishlist_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Wishlist to the html form elements
	if err := c.Bind(wishlist); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(wishlist)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, wishlist))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Wishlist was updated successfully")

	// and redirect to the wishlists index page
	return c.Render(200, r.Auto(c, wishlist))
}

// Destroy deletes a Wishlist from the DB. This function is mapped
// to the path DELETE /wishlists/{wishlist_id}
func (v WishlistsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Wishlist
	wishlist := &models.Wishlist{}

	// To find the Wishlist the parameter wishlist_id is used.
	if err := tx.Find(wishlist, c.Param("wishlist_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(wishlist); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Wishlist was destroyed successfully")

	// Redirect to the wishlists index page
	return c.Render(200, r.Auto(c, wishlist))
}
